name: check-abi
on:
  - push
  - pull_request

jobs:
  test-ABI:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: update
        run: sudo apt-get update
      - name: dependencies
        run: >
          sudo apt-get install --yes gcc
          gcc make pkg-config abigail-tools
          libdevmapper-dev libreadline-dev libaio-dev libsystemd-dev
          libudev-dev libjson-c-dev liburcu-dev libcmocka-dev libedit-dev
          libmount-dev
      - name: compare ABI against reference
        id: compare
        continue-on-error: true
        run: make abi-test
      - name: save differences
        if: ${{ steps.compare.outcome == 'failure' }}
        uses: actions/upload-artifact@v1
        with:
          name: abi-test
          path: abi-test
      - name: fail
        if: ${{ steps.compare.outcome == 'failure' }}
        run: false
