name: compile and unit test on foreign arch
on:
  push:
    branches:
      - master
      - queue
      - tip
      - 'stable-*'
    paths:
      - '.github/workflows/foreign.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'
  pull_request:
    branches:
      - master
      - queue
      - 'stable-*'
    paths:
      - '.github/workflows/foreign.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'

jobs:

  cross-build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        os: [bullseye, bookworm, trixie, sid]
        arch: [ppc64le, arm64, s390x]
        exclude:
          - os: bullseye
            arch: ppc64le
          - os: bullseye
            arch: s390x
    container: ghcr.io/mwilck/multipath-cross-debian_cross-${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: build
        run: make -j$(nproc) -Orecurse test-progs.tar
      - name: upload binary archive
        uses: actions/upload-artifact@v7
        with:
          name: cross-${{ matrix.os }}-${{ matrix.arch }}
          path: test-progs.tar
          overwrite: true

  test:
    runs-on: ubuntu-24.04
    needs: cross-build
    strategy:
      fail-fast: false
      matrix:
        os: [bullseye, bookworm, trixie, sid]
        arch: [ppc64le, arm64, s390x]
        exclude:
          - os: bullseye
            arch: ppc64le
          - os: bullseye
            arch: s390x
    steps:
      - name: set container arch
        run: echo CONTAINER_ARCH="${{ matrix.arch }}" >> $GITHUB_ENV
        if: matrix.arch != 'armhf'
      - name: set container arch
        run: echo CONTAINER_ARCH="arm/v7" >> $GITHUB_ENV
        if: matrix.arch == 'armhf'
      - name: download binary archive
        uses: actions/download-artifact@v4
        with:
          name: cross-${{ matrix.os }}-${{ matrix.arch }}
      - name: unpack binary archive
        run: tar xfv test-progs.tar
      - name: enable foreign arch
        uses: docker/setup-qemu-action@v4
        with:
          image: tonistiigi/binfmt:latest
      - name: Set coredump pattern
        run: |
          echo 'core.%e.%p' | sudo tee /proc/sys/kernel/core_pattern
      - name: run tests
        id: test
        run: |
          docker run \
            --pids-limit 4096 \
            --workdir /__w/multipath-tools/multipath-tools \
            --platform linux/${{ env.CONTAINER_ARCH }} \
            -w /__w/multipath-tools/multipath-tools \
            -v${{ github.workspace }}:/__w/multipath-tools/multipath-tools \
            ghcr.io/mwilck/multipath-run-debian-${{ matrix.os }} -C tests
        continue-on-error: true
      - name: Make core dumps accessible
        run: |
          find . \( -name 'core*' \) -print0 | xargs -0 -r sudo chmod a+x
        if: steps.test.outcome != 'success'
      - name: save test outputs
        run: make test-outputs.tar
        if: steps.test.outcome != 'success'
      - name: upload test outputs
        uses: actions/upload-artifact@v7
        with:
          name: test-${{ matrix.os }}-${{ matrix.arch }}
          path: test-outputs.tar
          overwrite: true
        if: steps.test.outcome != 'success'
      - name: fail if test failed
        run: /bin/false
        if: steps.test.outcome != 'success'

  root-test:
    runs-on: ubuntu-24.04
    needs: cross-build
    strategy:
      fail-fast: false
      matrix:
        os: [bullseye, bookworm, trixie, sid]
        arch: [ppc64le, arm64, s390x]
        exclude:
          - os: bullseye
            arch: ppc64le
          - os: bullseye
            arch: s390x
    steps:
      - name: mpath
        run: sudo modprobe dm_multipath
      - name: brd
        run: sudo modprobe brd rd_nr=1 rd_size=65536
      - name: set container arch
        run: echo CONTAINER_ARCH="${{ matrix.arch }}" >> $GITHUB_ENV
        if: matrix.arch != 'armhf'
      - name: set container arch
        run: echo CONTAINER_ARCH="arm/v7" >> $GITHUB_ENV
        if: matrix.arch == 'armhf'
      - name: download binary archive
        uses: actions/download-artifact@v4
        with:
          name: cross-${{ matrix.os }}-${{ matrix.arch }}
      - name: unpack binary archive
        run: tar xfv test-progs.tar
      - name: enable foreign arch
        uses: docker/setup-qemu-action@v4
        with:
          image: tonistiigi/binfmt:latest
      - name: Set coredump pattern
        run: |
          echo 'core.%e.%p' | sudo tee /proc/sys/kernel/core_pattern
      - name: run tests
        id: root-test
        run: |
          docker run \
            --workdir /__w/multipath-tools/multipath-tools \
            --pids-limit 4096 \
            --platform linux/${{ env.CONTAINER_ARCH }} \
            --privileged \
            -v /dev/ram0:/dev/ram0 -e DIO_TEST_DEV=/dev/ram0 \
            -w /__w/multipath-tools/multipath-tools \
            -v${{ github.workspace }}:/__w/multipath-tools/multipath-tools \
            ghcr.io/mwilck/multipath-run-debian-${{ matrix.os }} \
            -C tests dmevents.out
        continue-on-error: true
      - name: Make core dumps accessible
        run: |
          find . \( -name 'core*' \) -print0 | xargs -0 -r sudo chmod a+x
        if: steps.root-test.outcome != 'success'
      - name: save test outputs
        run: make test-outputs.tar
        if: steps.root-test.outcome != 'success'
      - name: upload test outputs
        uses: actions/upload-artifact@v7
        with:
          name: root-test-${{ matrix.os }}-${{ matrix.arch }}
          path: test-outputs.tar
          overwrite: true
        if: steps.root-test.outcome != 'success'
      - name: fail if root test failed
        run: /bin/false
        if: steps.root-test.outcome != 'success'
