name: compile and unit test on foreign arch
on:
  push:
    branches:
      - master
      - queue
      - tip
      - next
      - factory
      - sles*
    paths:
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'
  pull_request:
    branches:
      - master
      - queue
    paths:
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'

jobs:

  cross-build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os: [bookworm, sid]
        arch: [ppc64le, arm64, s390x]
    container: ghcr.io/mwilck/multipath-cross-debian_cross-${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build
        run: make -j8 -Orecurse TESTDIR=/build/tests test-progs
      - name: create binary archive
        run: >
          tar cfv binaries.tar
          Makefile* config.mk
          libmpathcmd/*.so* libmultipath/*.so* libmpathutil/*.so*
          libmultipath/checkers/*.so libmultipath/prioritizers/*.so
          libmultipath/foreign/*.so
          tests/lib tests/*-test tests/Makefile tests/*.so*
      - name: upload binary archive
        uses: actions/upload-artifact@v1
        with:
          name: cross-${{ matrix.os }}-${{ matrix.arch }}
          path: binaries.tar

  test:
    runs-on: ubuntu-22.04
    needs: cross-build
    strategy:
      fail-fast: false
      matrix:
        os: [bookworm, sid]
        arch: [ppc64le, arm64, s390x]
    steps:
      - name: set container arch
        run: echo CONTAINER_ARCH="${{ matrix.arch }}" >> $GITHUB_ENV
        if: ${{ matrix.arch != 'armhf' }}
      - name: set container arch
        run: echo CONTAINER_ARCH="arm/v7" >> $GITHUB_ENV
        if: ${{ matrix.arch == 'armhf' }}
      - name: download binary archive
        uses: actions/download-artifact@v1
        with:
          name: cross-${{ matrix.os }}-${{ matrix.arch }}
      - name: unpack binary archive
        run: tar xfv cross-${{ matrix.os }}-${{ matrix.arch }}/binaries.tar
      - name: enable foreign arch
        uses: dbhi/qus/action@main
      - name: run tests
        uses: mosteo-actions/docker-run@v1
        with:
          image: ghcr.io/mwilck/multipath-run-debian-${{ matrix.os }}
          guest-dir: /build
          host-dir: ${{ github.workspace }}
          command: -C tests
          params: "--platform linux/${{ env.CONTAINER_ARCH }}"
          pull-params: "--platform linux/${{ env.CONTAINER_ARCH }}"
