name: multiarch test for stable distros
on:
  push:
    branches:
      - master
      - queue
      - tip
    paths:
      - '.github/workflows/multiarch-stable.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'
  pull_request:
    branches:
      - master
      - queue
    paths:
      - '.github/workflows/multiarch-stable.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'
jobs:

  build-old:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-bookworm
          - debian-buster
          - ubuntu-trusty
        arch: [386, arm/v7]
        include:
          - os: debian-bookworm
            arch: aarch64
          - os: debian-bookworm
            arch: s390x
          - os: debian-bookworm
            arch: ppc64le
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: enable foreign arch
        uses: dbhi/qus/action@main
      - name: compile and run unit tests
        uses: mosteo-actions/docker-run@v1
        with:
          image: ghcr.io/mwilck/multipath-build-${{ matrix.os }}
          guest-dir: /build
          host-dir: ${{ github.workspace }}
          command: test
          params: "--platform linux/${{ matrix.arch }}"
          pull-params: "--platform linux/${{ matrix.arch }}"
