name: multiarch test for stable distros
on:
  push:
    branches:
      - master
      - queue
      - tip
      - 'stable-*'
    paths:
      - '.github/workflows/multiarch-stable.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'
  pull_request:
    branches:
      - master
      - queue
      - 'stable-*'
    paths:
      - '.github/workflows/multiarch-stable.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'
jobs:

  build-old:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-trixie
          - debian-bookworm
          - debian-buster
          - ubuntu-trusty
        arch: [386, arm/v7]
        include:
          - os: debian-trixie
            arch: s390x
          - os: debian-trixie
            arch: ppc64le
          - os: debian-bookworm
            arch: s390x
          - os: debian-bookworm
            arch: ppc64le
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: enable foreign arch
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
      - name: set architecture name
        run: |
          __arch="${{ matrix.arch }}"
          echo "ARCH_NAME=${__arch//\//-}" >>"$GITHUB_ENV"
      - name: Set coredump pattern
        run: |
          echo 'core.%e.%p' | sudo tee /proc/sys/kernel/core_pattern
      - name: compile and run unit tests
        id: test
        run: |
          docker run --pids-limit 4096 --platform linux/${{ matrix.arch }} \
            -w /build -v${{ github.workspace }}:/build \
            ghcr.io/mwilck/multipath-build-${{ matrix.os }} test
        continue-on-error: true
      - name: create binary archive
        run: |
          docker run --platform linux/${{ matrix.arch }} \
            -w /build -v${{ github.workspace }}:/build \
            ghcr.io/mwilck/multipath-build-${{ matrix.os }} test-progs.tar
        if: steps.test.outcome != 'success'
      - name: upload binary archive
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}-${{ env.ARCH_NAME }}
          path: test-progs.tar
          overwrite: true
        if: steps.test.outcome != 'success'
      - name: save test outputs
        run: make test-outputs.tar
        if: steps.test.outcome != 'success'
      - name: upload test outputs
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ matrix.os }}-${{ env.ARCH_NAME }}
          path: test-outputs.tar
          overwrite: true
        if: steps.test.outcome != 'success'
      - name: fail if test failed
        run: /bin/false
        if: steps.test.outcome != 'success'
