name: multiarch test for rolling distros
on:
  push:
    branches:
      - master
      - queue
      - tip
      - 'stable-*'
    paths:
      - '.github/workflows/multiarch.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'
  pull_request:
    branches:
      - master
      - queue
      - 'stable-*'
    paths:
      - '.github/workflows/multiarch.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'
  # run monthly to catch rolling distro changes
  schedule:
    - cron: '45 02 1 * *'

jobs:

  build-current:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - alpine
          - debian-sid
          - fedora-rawhide
          - opensuse-tumbleweed
        arch: [ppc64le, s390x, 386, arm/v7]
        exclude:
          - os: fedora-rawhide
            arch: 386
          - os: fedora-rawhide
            arch: arm/v7
        include:
          - os: alpine
            arch: aarch64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: enable foreign arch
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
      - name: set architecture name
        run: |
          __arch="${{ matrix.arch }}"
          echo "ARCH_NAME=${__arch//\//-}" >>"$GITHUB_ENV"
      - name: compile and run unit tests
        id: test
        run: |
          docker run --pids-limit 4096 --platform linux/${{ matrix.arch }} \
            -w /build -v${{ github.workspace }}:/build \
            ghcr.io/mwilck/multipath-build-${{ matrix.os }} test
        continue-on-error: true
      - name: create archives
        run: |
          docker run --platform linux/${{ matrix.arch }} \
            -w /build -v${{ github.workspace }}:/build \
            ghcr.io/mwilck/multipath-build-${{ matrix.os }} test-progs.tar test-outputs.tar
        if: steps.test.outcome != 'success'
      - name: upload binary archive
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}w-${{ env.ARCH_NAME }}
          path: test-progs.tar
        if: steps.test.outcome != 'success'
      - name: upload test outputs
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ matrix.os }}-${{ env.ARCH_NAME }}
          path: test-outputs.tar
          overwrite: true
        if: steps.test.outcome != 'success'
      - name: fail if test failed
        run: /bin/false
        if: steps.test.outcome != 'success'
