name: compile and unit test on Leap
on:
  push:
    branches:
      - sles*
      - factory
      - next
      - edge
    paths:
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os: ['tumbleweed', '15.3', '15.4', '15.5', '15.6']
        # We have -arm too (for armv7l)
        # But tests fail with qemu-user (readdir() returns -EOVERFLOW), see
        # https://gitlab.com/qemu-project/qemu/-/issues/263
        # https://sourceware.org/bugzilla/show_bug.cgi?id=23960
        # Attempts to fix this with -D_FILE_OFFSET_BITS=64 failed, too
        # this means replacing cmocka wrappers like __wrap_lseek() with
        # __wrap_lseek64()
        arch: ['x86_64', 'ppc64le', 'aarch64', 's390x']
    steps:
      - name: set repository and container name (TW)
        run: |
          echo "REPO_NAME=${{ matrix.os }}" >> $GITHUB_ENV
          echo "CONT_NAME=multipath-build-opensuse-tumbleweed-latest" >> $GITHUB_ENV
        if: ${{ matrix.os == 'tumbleweed' }}
      - name: set repository and container name (SLE)
        run: |
          echo "${{ matrix.os }}" | \
              sed -E 's/15.([0-9]*)/REPO_NAME=sle_15_sp\1/' >> $GITHUB_ENV
          echo "CONT_NAME=multipath-build-sles-15-${{ matrix.os }}" >> $GITHUB_ENV
        if: ${{ startswith( matrix.os, '15') }}
      - name: checkout
        uses: actions/checkout@v1
      - name: enable foreign arch
        run: sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: build and run unit tests
        # Github actions doesn't support referencing docker images with
        # context variables. Workaround: use mosteo-actions/docker-run action
        # See https://github.community/t/expressions-in-docker-uri/16271
        uses: mosteo-actions/docker-run@v1
        with:
          params: --platform ${{ matrix.arch }}
          image: registry.opensuse.org/home/mwilck/containers/${{ env.REPO_NAME }}/${{ env.CONT_NAME }}
          command: test
