name: compile and unit test on Leap
on:
  push:
    branches:
      - sles*
      - factory
      - next

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: ['leap15.2']
        arch: ['', '-ppc64le', '-arm64', '-arm']
        include:
          - os: 'leap15.3'
            arch: '-s390x'
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: enable foreign arch
        run: sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: build and run unit tests
        # Github actions doesn't support referencing docker images with
        # context variables. Workaround: use mosteo-actions/docker-run action
        # See https://github.community/t/expressions-in-docker-uri/16271
        uses: mosteo-actions/docker-run@v1
        with:
          image: mwilck/multipath-build-${{ matrix.os }}${{ matrix.arch }}
          command: test

